apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
data:
  config.json: |
    {
      "api_url": "https://queue.stg.austinbayley.co.uk",
      "queue": "default",
      "account_url": "https://account.stg.austinbayley.co.uk"
    }